### 降维-手写数字识别

In [1]:
import numpy as np
import pandas as pd

#### 加载数据

In [2]:
data = pd.read_csv('./digits.csv')
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [3]:
y = data['label']
X = data.iloc[:,1:]
display(y.head(),X.head())

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [ ]:
X.shape

#### 展示数据

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
y

In [ ]:
# 784像素，28行和28列组成的 
image = X.iloc[41997].values.reshape(28,28)
plt.figure(figsize=(2,2))
plt.imshow(image,cmap='gray')

#### 数据拆分

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 1000,random_state = 0)
display(X_train.shape,X_test.shape)

(41000, 784)

(1000, 784)

#### 建模【逻辑斯蒂回归】

In [ ]:
%%time
# from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_ = model.predict(X_test)
display(y_test[:20],y_[:20])

In [ ]:
%%time
model.score(X_test,y_test) #模型进行预测时花费时间比较长

#### 数据降维

In [8]:
from sklearn.decomposition import PCA

In [9]:
pca = PCA(n_components=0.95) 
# 标准化处理，算法KNN，距离计算，不需要标准化，如果是梯度下降算法【必须归一化】
X_pca = pca.fit_transform(X)
display(X.shape,X_pca.shape)
display(X_pca[:5])

(42000, 784)

(42000, 154)

array([[-6.61595780e+02, -6.99311328e+02,  1.83282040e+02,
         1.20611394e+02, -8.10818105e+01,  4.89461886e+02,
        -6.83470838e+02,  8.55593866e+01,  3.48548052e+02,
         2.02978545e+02, -3.64559949e+02,  2.12657559e+01,
         4.04441449e+02, -9.70525455e+01,  6.18399356e+01,
        -8.67800272e+01,  1.76581436e+01,  2.85484696e+02,
         1.88273028e+01,  2.07642731e+02,  4.42436003e+01,
         2.21894370e+02,  5.72274592e+01, -1.48674962e+02,
         1.43435889e+01, -4.15560311e+01, -3.33723659e+02,
         2.08978881e+02,  5.98136306e+01,  8.45544647e+01,
         6.94293060e+00, -5.29995065e+00,  1.95709336e+02,
        -5.32292285e+01, -6.88959872e+00, -1.46886583e+02,
        -4.94066227e+01, -8.80639802e+01, -1.61589210e+02,
        -1.40787617e+02,  1.04959060e+02,  2.00310607e+01,
         4.15619445e+01, -3.65287408e+01, -2.06185633e+02,
         3.34091629e+01, -5.41183777e+01, -5.62953193e+01,
        -7.53699522e+01,  6.90935930e+01,  7.33123981e+0

In [10]:
X_train_pca,X_test_pca,y_train,y_test = train_test_split(X_pca,y,test_size = 1000,random_state = 0)

In [ ]:
%%time
knn = KNeighborsClassifier()

knn.fit(X_train_pca,y_train)

y_ = knn.predict(X_test_pca)
display(y_test.values[:20],y_[:20])

In [ ]:
knn.score(X_test_pca,y_test)

#### 探索逻辑斯蒂回归【出错】

In [ ]:
pip list

In [ ]:
pip list

In [6]:
%%time
from sklearn.linear_model import LogisticRegression # 刚才的错，sklearn版本的问题，升级了一下，截距
model =LogisticRegression(max_iter=5000)
model.fit(X_train,y_train)
y_ = model.predict(X_test)
display(y_test[:20],y_[:20])

d:\soft\python\396\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


16275    3
19204    6
18518    9
25780    5
16228    6
15824    5
29252    6
28482    0
13779    0
25912    1
27141    7
21848    1
32576    5
7975     7
10594    8
37445    1
12928    1
2747     5
6658     9
8966     6
Name: label, dtype: int64

array([3, 6, 9, 5, 6, 0, 6, 0, 0, 1, 7, 1, 5, 7, 8, 1, 1, 5, 9, 6],
      dtype=int64)

CPU times: total: 1h 25min 34s
Wall time: 8min 10s


In [7]:
%%time
model.score(X_test,y_test)

CPU times: total: 15.6 ms
Wall time: 9.98 ms


0.901

In [11]:
%%time
# PCA降维没有进行归一化
from sklearn.linear_model import LogisticRegression # 刚才的错，sklearn版本的问题，升级了一下，截距
model =LogisticRegression(max_iter=5000)
model.fit(X_train_pca,y_train)
y_ = model.predict(X_test_pca)
display(y_test[:20],y_[:20])
model.score(X_test_pca,y_test)

d:\soft\python\396\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


16275    3
19204    6
18518    9
25780    5
16228    6
15824    5
29252    6
28482    0
13779    0
25912    1
27141    7
21848    1
32576    5
7975     7
10594    8
37445    1
12928    1
2747     5
6658     9
8966     6
Name: label, dtype: int64

array([3, 6, 9, 5, 6, 0, 6, 0, 0, 1, 7, 1, 5, 7, 8, 1, 1, 5, 9, 6],
      dtype=int64)

CPU times: total: 20min 13s
Wall time: 3min


0.928

#### 降维时候，归一化

In [12]:
pca = PCA(n_components=0.95,whiten=True) 
# 标准化处理，算法KNN，距离计算，不需要标准化，如果是梯度下降算法【必须归一化】
X_pca = pca.fit_transform(X)
X_train_pca,X_test_pca,y_train,y_test = train_test_split(X_pca,y,test_size = 1000,random_state = 0)

In [13]:
%%time
# PCA降维进行归一化
from sklearn.linear_model import LogisticRegression # 刚才的错，sklearn版本的问题，升级了一下，截距
model =LogisticRegression(max_iter=5000)
model.fit(X_train_pca,y_train)
y_ = model.predict(X_test_pca)
display(y_test[:20],y_[:20])
model.score(X_test_pca,y_test)

16275    3
19204    6
18518    9
25780    5
16228    6
15824    5
29252    6
28482    0
13779    0
25912    1
27141    7
21848    1
32576    5
7975     7
10594    8
37445    1
12928    1
2747     5
6658     9
8966     6
Name: label, dtype: int64

array([3, 6, 9, 5, 6, 0, 6, 0, 0, 1, 7, 1, 5, 7, 8, 1, 1, 5, 9, 6],
      dtype=int64)

CPU times: total: 35.8 s
Wall time: 5.38 s


0.929

### LDA线性判别

In [14]:
from sklearn import datasets

In [15]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [16]:
X,y = datasets.load_iris(return_X_y=True)

In [17]:
# solver : {'svd', 'lsqr', 'eigen'}
lda = LinearDiscriminantAnalysis(solver='eigen',n_components=2)

In [35]:
X_lda = lda.fit_transform(X,y) # 有监督，数据X对应着y
# pca.fit_transform(X) # 无监督，只需要传入X，降维

### 自己写代码完成LDA操作

In [30]:
np.set_printoptions(suppress=True)

In [37]:
# scipy比numpy更加高级的科学计算库
# pip install scipy
from scipy import linalg # 线性代数
# 1、总的散度矩阵
# 协方差，计算的列的,Scatter _ total
St = np.cov(X.T,rowvar = True,bias = 1) # bias偏差，截距
# 2、类内散度矩阵，分3类：0、1、2
# Sw within类内
Sw = np.full(shape = (4,4),fill_value=0,dtype=np.float64) # 声明了一个空的，全是0
for i in range(3): # i = 0,1,2
    Sw += np.cov(X[y ==i],rowvar=False,bias=1)
Sw/=3 # 三个类别的平均【类内的散度矩阵】
# 3、计算类间的散度矩阵
Sb = St - Sw
# 4、计算特征值和特征向量
eigen,ev = linalg.eigh(Sb,Sw) # 类间和类内，特征值从小到大
np.argsort(eigen) # 排序索引
n_components = 2
ev = ev[:,[3,2,1,0]][:,:n_components] # 从大到小
# 5、进行矩阵运算
X.dot(ev)[:5]

array([[6.01716893, 7.03257409],
       [5.0745834 , 5.9344564 ],
       [5.43939015, 6.46102462],
       [4.75589325, 6.05166375],
       [6.08839432, 7.24878907]])

In [36]:
X_lda[:5]

array([[6.01716893, 7.03257409],
       [5.0745834 , 5.9344564 ],
       [5.43939015, 6.46102462],
       [4.75589325, 6.05166375],
       [6.08839432, 7.24878907]])